---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    author: chaitanya
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    author: chaitanya
    type: proxy

